version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    container_name: my-postgres-container
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - /path/on/host/Postgres-data:/var/lib/postgresql/data
      #change "/path/on/host" to your path
